/*----------------------------------------------------------
MASV:
HO TEN CAC THANH VIEN NHOM:
	+ Nguyễn Hoàng Anh Tú
	+ Cao Đức Minh
	+ Nguyễn Thiện Thanh
	+ Đàm Nhật Phong
	+ Đỗ Phúc Hậu
LAB: 03 - NHOM
NGAY:
----------------------------------------------------------*/
CREATE DATABASE QLSV_NHOM
USE QLSV_NHOM;


CREATE TABLE SINHVIEN (
	MASV NVARCHAR(20) NOT NULL,
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(500) NOT NULL,
)

CREATE TABLE LOP(
	MALOP VARCHAR(20) NOT NULL,
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20)
)
CREATE TABLE NHANVIEN(
	MANV VARCHAR(20) NOT NULL,
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(500),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(500) NOT NULL,
	PUBKEY VARCHAR(20) NOT NULL,
)
CREATE TABLE HOCPHAN(
	MAHP VARCHAR(20) NOT NULL,
	TENHP NVARCHAR(100) NOT NULL,
	SOTC INT
)
CREATE TABLE BANGDIEM(
	MASV NVARCHAR(20) NOT NULL,
	MAHP VARCHAR(20) NOT NULL,
	DIEMTHI VARBINARY,
)


ALTER TABLE NHANVIEN
ADD CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV)
GO

ALTER TABLE LOP 
ADD CONSTRAINT PK_LOP PRIMARY KEY (MALOP)
GO

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_NHANVIEN
FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
GO

ALTER TABLE SINHVIEN 
ADD CONSTRAINT PK_SINHVIEN PRIMARY KEY (MASV)
GO

ALTER TABLE SINHVIEN
ADD CONSTRAINT FK_SINHVIEN_LOP
FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
GO

ALTER TABLE HOCPHAN
ADD CONSTRAINT PK_HOCPHAN
PRIMARY KEY (MAHP)


ALTER TABLE BANGDIEM
ADD CONSTRAINT PF_BANGDIEM
PRIMARY KEY (MASV,MAHP)

ALTER TABLE BANGDIEM 
ADD CONSTRAINT FK_BANGDIEM_SINHVIEN
FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV)

ALTER TABLE BANGDIEM 
ADD CONSTRAINT FK_BANGDIEM_HOCPHAN
FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP)


/* SP NHANVIEN*/

CREATE MASTER KEY ENCRYPTION BY   
PASSWORD = 'lab03';



SELECT *
FROM  sys.asymmetric_keys
GO


/* TẠO PROC NHANVIEN*/
CREATE PROC SP_INS_PUBLIC_NHANVIEN @MANV NVARCHAR(20),@HOTEN NVARCHAR(100),@EMAIL VARCHAR(20) ,
		@LUONG VARCHAR(100), @TENDN NVARCHAR(100),@MATKHAU NVARCHAR(20)	
as
BEGIN 
	PRINT @LUONG

	DECLARE @ENCRYPTEDPASSWORD VARBINARY(500)
	SET @ENCRYPTEDPASSWORD = HASHBYTES('SHA1', @MATKHAU);
	
	DECLARE @CREATEKEY NVARCHAR(MAX) = '
	CREATE ASYMMETRIC KEY Encrypt_Salary'+@MANV+'
	WITH ALGORITHM = RSA_512
	encryption by password = '''+@MATKHAU+'''';
	EXECUTE(@CREATEKEY)
	INSERT INTO NHANVIEN
	VALUES (@MANV,@HOTEN,@EMAIL,ENCRYPTBYASYMKEY(ASYMKEY_ID('Encrypt_Salary'+@MANV),@LUONG),@TENDN,@ENCRYPTEDPASSWORD,@MANV)
END
GO

/* TRUY XUAT NHANVIEN*/
CREATE PROC SP_SEL_PUBLIC_NHANVIEN @MANV VARCHAR(20), @MATKHAU NVARCHAR(100)
AS
BEGIN
	DECLARE @CHECKMATKHAU NVARCHAR(20) 
	SELECT @CHECKMATKHAU = MATKHAU FROM NHANVIEN WHERE MANV = @MANV;
	IF(HASHBYTES('SHA1',@MATKHAU) = @CHECKMATKHAU)
		BEGIN
			SELECT MANV, HOTEN , EMAIL,CONVERT(VARCHAR(200),DECRYPTBYASYMKEY(ASYMKEY_ID('Encrypt_Salary'+@MANV),LUONG,@MATKHAU)) LUONG FROM NHANVIEN WHERE MANV = @MANV
		END
	ELSE
		BEGIN
			PRINT('INVALID PASSWORD');
		END
END

EXEC SP_SEL_PUBLIC_NHANVIEN 'NV02', '1234567'

/* đăng nhập nhan vien*/
EXEC sp_helptext 'QLSV.dbo.CLIENT_LOGIN';
IF OBJECT_ID('dbo.NHANVIEN_LOGIN', 'P') IS NOT NULL  
   DROP PROCEDURE dbo.NHANVIEN_LOGIN;  
GO  

CREATE PROC NHANVIEN_LOGIN @USERNAME NVARCHAR(100), @PASSWORD NVARCHAR(100)						
AS
BEGIN
	SELECT * FROM NHANVIEN AS NV WHERE NV.TENDN = @USERNAME AND CONVERT(NVARCHAR(500),NV.MATKHAU,2) = @PASSWORD
	RETURN 
END
GO

/*dang nhap sinh vien*/
IF OBJECT_ID('dbo.SINHVIEN_LOGIN', 'P') IS NOT NULL  
   DROP PROCEDURE dbo.SINHVIEN_LOGIN;  
GO  

CREATE PROC SINHVIEN_LOGIN @USERNAME NVARCHAR(100), @PASSWORD NVARCHAR(100)						
AS
BEGIN	
	SELECT * FROM SINHVIEN AS SV WHERE SV.TENDN = @USERNAME AND CONVERT(NVARCHAR(200),SV.MATKHAU,2) = @PASSWORD
END
GO

EXEC SP_INS_PUBLIC_NHANVIEN N'NV01', N'NGUYEN VAN A', N'nva@yahoo.com', 3000000,
N'NVA', N'123456'
GO

EXEC SP_INS_PUBLIC_NHANVIEN N'NV02', N'NGUYEN VAN B', N'nvb@yahoo.com', 2000000,
N'NVB', N'1234567'
GO